### PR TITLE
[WIP] Chinese translation

### PR DESCRIPTION
**Pull request by MercierCorentin**
Work by @JulesPer 
Enjoy!

### CODE REVIEW

**Comment by aarrtthhuurr** [comment]
Awesome work!

**Comment by NastuzziSamy** [comment]
Good to go ! :) Even if it is not fully translated like it is shown here:

68481095_372783610083439_3728277847698046976_n

**Comment by MercierCorentin** [comment]
Dependencies were removed because it is too hard to translate, we are good with the Chinese translation I think.

**Comment by NastuzziSamy** [comment]
I let you @MercierCorentin merge when you think it is good to go 😊

**Comment by NastuzziSamy** [comment]
Ok actually, I will make some fixes, the json is no more valid + you do not need to duplicate french translations in the chinese tranlation file. The application auto fallbacks ;)

**Pull request merged**
